Implement overlay on recorded videos by using subtitles
Williangalvani/qgroundcontrol pull request #1
Opened 2019-04-26 22:40 UTC by Williangalvani

This enables QGC to record a data overlay while recording the video. The overlay is a subtitle in the [SubStation Alpha](https://en.wikipedia.org/wiki/SubStation_Alpha) format, which can be easily enabled/disabled.  For every video file, there is also a subtitle file.

This helps user to have all flight data necessary on an overlay without encoding it to the video itself.
The result looks like this:
![Screenshot from 2019-04-26 19-33-18](https://user-images.githubusercontent.com/4013804/56839846-e16eef80-685a-11e9-8d1d-fb60276f33ee.png)

2019-05-13 17:50 UTC, jaxxzer commented
might need a rebase on upstream/master

2019-05-13 18:42 UTC, jaxxzer requested changes

2019-05-13 18:42 UTC, jaxxzer commented on src/FlightDisplay/VideoManager.cc
> +        _subtitleWriter = new SubtitleWriter();
You are manually allocating memory. You must also deallocate it.

```suggestion
        if (_subtitleWriter) {
            delete _subtitleWriter;
        }
        _subtitleWriter = new SubtitleWriter;
```

Also in the constructor:
```
delete _subtitleWriter
```

HOWEVER, this class member `_subtitleWriter` is static (it does not need to be changed/reinitialized at any point during the VideoReceiver owner's lifetime). Therefore, `_subtitleWriter` should be declared as:
```
SubtitleWriter _subtitleWriter; // non-pointer type
```

2019-05-13 18:46 UTC, jaxxzer requested changes

2019-05-13 18:46 UTC, jaxxzer commented on src/VideoStreaming/VideoReceiver.cc
> +VideoReceiver::getRecordingTime()
There is a problem in the current implementation, the timestamps in the output of the subtitle file are not monotonic:

```
[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,999:00:00.00,Default,,0,0,0,,{\pos(10,35)}13 May 2019
Dialogue: 0,0:00:18.997,0:00:01.993,Default,,0,0,0,,{\an3\pos(295,1075)}Depth:\NGround Speed:\NDive Time:\NRoll:
Dialogue: 0,0:00:18.997,0:00:01.993,Default,,0,0,0,,{\pos(305,1075)}0.0 m\N0.0 m/s\N00:00:00 \N-111.2 deg
Dialogue: 0,0:00:18.997,0:00:01.993,Default,,0,0,0,,{\an3\pos(950,1075)}Pitch:\NHeading:\NDistance to Home:\NHeading to Home:
Dialogue: 0,0:00:18.997,0:00:01.993,Default,,0,0,0,,{\pos(960,1075)}-10.1 deg\N180 deg\N39.3 m\N4 deg
Dialogue: 0,0:00:18.997,0:00:01.993,Default,,0,0,0,,{\an3\pos(1605,1075)}Latitude:\NLongitude:
Dialogue: 0,0:00:18.997,0:00:01.993,Default,,0,0,0,,{\pos(1615,1075)}63.4426060 \N10.4236482 
Dialogue: 0,0:00:01.993,0:00:02.997,Default,,0,0,0,,{\an3\pos(295,1075)}Depth:\NGround Speed:\NDive Time:\NRoll:
Dialogue: 0,0:00:01.993,0:00:02.997,Default,,0,0,0,,{\pos(305,1075)}0.0 m\N0.0 m/s\N00:00:00 \N-111.2 deg
Dialogue: 0,0:00:01.993,0:00:02.997,Default,,0,0,0,,{\an3\pos(950,1075)}Pitch:\NHeading:\NDistance to Home:\NHeading to Home:
Dialogue: 0,0:00:01.993,0:00:02.997,Default,,0,0,0,,{\pos(960,1075)}-10.2 deg\N180 deg\N37.5 m\N2 deg
Dialogue: 0,0:00:01.993,0:00:02.997,Default,,0,0,0,,{\an3\pos(1605,1075)}Latitude:\NLongitude:
Dialogue: 0,0:00:01.993,0:00:02.997,Default,,0,0,0,,{\pos(1615,1075)}63.4426208 \N10.4236673 
Dialogue: 0,0:00:02.997,0:00:03.992,Default,,0,0,0,,{\an3\pos(295,1075)}Depth:\NGround Speed:\NDive Time:\NRoll:
```

The time in the first time stamp (18.997) varies, and appears to be related to the amount of time it takes for the video to come back after starting recording (that first i-frame thing).

NOTE We do not necessarily need to use the pipeline/filesink clock. We can just use wall clock (os/system time).

2019-05-13 18:46 UTC, jaxxzer commented
Please write round/integral values for the timestamps (instead of .997 or .001).

2019-05-13 18:47 UTC, jaxxzer requested changes
Please write round/integral values for the timestamps (instead of .997 or .001).

2019-05-13 18:51 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.h
> +    void _update();
```suggestion
    void _onVideoRecordingChanged();
```

2019-05-13 18:51 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.h
> +    // keys to read vehicle facts
```suggestion

    // keys to read vehicle facts
```

2019-05-13 18:59 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +    _timer.start(1000);
This should come after the file access in this function.

2019-05-13 19:06 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +"PlayResX: 1920\n"
I didn't expect this patch to work with the stream resolution set to 640x480.. but it does.

2019-05-15 14:31 UTC, Williangalvani commented
> Please write round/integral values for the timestamps (instead of .997 or .001).

What if I reduce the precision to 1 decimal place? It would be simpler but still precise enough (~3 frames resolution @ 30fps)

2019-05-15 14:44 UTC, jaxxzer commented
I prefer integers from a readability/filesize standpoint. We do not require any more precision than that.

> simpler

What's the issue with writing integers? You are in control of the format string, convert the float time to integer.

2019-05-15 15:02 UTC, Williangalvani commented
> What's the issue with writing integers? You are in control of the format string, convert the float time to integer.

Because deep inside I wanted to push the sample rate a little higher, 2 or 3hz

2019-05-15 15:05 UTC, Williangalvani commented on src/VideoStreaming/VideoReceiver.cc
> +VideoReceiver::getRecordingTime()
I did it like that because I worried that after a long time time could diverge too much.
GStreamer and videos work in a mysterious way, after all.

I'm checking the monotonic issue.

2019-05-15 19:27 UTC, jaxxzer commented on src/VideoStreaming/VideoReceiver.cc
> +VideoReceiver::getRecordingTime()
> because I worried that after a long time time could diverge too much.

if we just look at the clock on the wall every timestamp, we are fine. There is no divergance that may happen. We are corellating our most recent telemetry to our most recent video frame.

However, in your current patch, you are looking at two different clocks, qt and gstreamer. Divergance is now a threat among other things.

I think if you move to only qt clock, your patch will be smaller and your monotonic problems will go away.

2019-05-15 19:30 UTC, jaxxzer commented
> Because deep inside I wanted to push the sample rate a little higher, 2 or 3hz

aha! I'll allow it

2019-05-15 19:33 UTC, Williangalvani commented on src/VideoStreaming/VideoReceiver.cc
> +VideoReceiver::getRecordingTime()
The monotonic issue was fixed by this:
https://github.com/Williangalvani/qgroundcontrol/pull/1/commits/3760569c63bb1336ddc01454f5fb4699eb3e8d08

2019-05-15 19:34 UTC, Williangalvani commented
> Please write round/integral values for the timestamps (instead of .997 or .001).

I just tested. VLC refuses to play files without decimal in the seconds, I assume it is trying to parse floats.

2019-05-15 19:35 UTC, jaxxzer commented on src/VideoStreaming/VideoReceiver.cc
> +VideoReceiver::getRecordingTime()
Will you please try some commits on top to move to only qt clock api?

2019-05-15 19:36 UTC, Williangalvani commented on src/VideoStreaming/VideoReceiver.cc
> +VideoReceiver::getRecordingTime()
okay!

2019-05-15 20:07 UTC, jaxxzer commented
> > Please write round/integral values for the timestamps (instead of .997 or .001).
> 
> I just tested. VLC refuses to play files without decimal in the seconds, I assume it is trying to parse floats.

Ok, at least round the value to regular intervals

2019-05-16 11:55 UTC, Williangalvani commented
> Edit: on second thought, is what I'm asking tenable? If we attempt this will we be accumulating some error based off the non-realtime behavior of QTimer?

It is doable, but we'll effectively be using a different timestamp for the data than when it was actually taken. And yes, QTimer implementation seems to differ from different platforms, that's why I did things this way.

2019-05-16 12:18 UTC, Williangalvani commented
About using the GStreamer time. The video is just being fed into a pipeline that writes it to a file. I don't know if the timing information comes from the h264 stream (rpi/camera), or from the muxer(local pc), or from somewhere else.
There is no guarantee that the time in that file is the same as the one for QGC.
So I made a QTimer to get periodic data, and for each time it fired, I got the data from the vehicle and the current timestamp from GStreamer.

2019-05-16 18:09 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +            // Fill templates for calues of column i
```suggestion
            // Fill templates for values of column i
```

2019-05-16 18:10 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +                                       .arg(_lastEndTime.toString("H:mm:ss.zzz").chopped(2))
```suggestion
                                       .arg(_lastTimeString)
```

2019-05-16 18:10 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +                                     .arg(_lastEndTime.toString("H:mm:ss.zzz").chopped(2))
```suggestion
                                     .arg(_lastTimeString)
```

2019-05-16 18:11 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +        QString startTimeString = _lastEndTime.toString("H:mm:ss.zzz").chopped(2);
```suggestion

        // the time to start displaying this subtitle text
        QString startTimeString = _lastEndTime.toString("H:mm:ss.zzz").chopped(2);
```

2019-05-16 18:12 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +        QTime start = QTime(0,0).addMSecs(QDateTime::currentDateTime().time().msecsTo(_startTime.time()));
```suggestion

        // The current time elapsed since recording started
        QTime currentTime = QTime(0,0).addMSecs(QDateTime::currentDateTime().time().msecsTo(_startTime.time()));
```

2019-05-16 18:13 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +        QString endTimeString = start.addMSecs(1000).toString("H:mm:ss.zzz").chopped(2);
```suggestion

        // the time to stop displaying this subtitle text
        QString endTimeString = start.addMSecs(1000).toString("H:mm:ss.zzz").chopped(2);
```

2019-05-16 18:14 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +        QTime start = QTime(0,0).addMSecs(QDateTime::currentDateTime().time().msecsTo(_startTime.time()));
will it be possible to remove the _lastEndTime logic entirely and just use this timestamp for both strings? They should always be equal, correct?

2019-05-16 18:16 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +void SubtitleWriter::setup()
should these be in the constructor @patrickelectric?

2019-05-16 19:27 UTC, patrickelectric requested changes

2019-05-16 19:27 UTC, patrickelectric commented on src/VideoStreaming/SubtitleWriter.cc
> +const int SubtitleWriter::offsetFactor = 700; // Used to simulate a larger resolution and reduce the borders in the layout
If rows and offsetFactor are privated, why you are not using the underscore prefix ?
That's the idea behind the underscore prefix right ?

2019-05-16 19:27 UTC, patrickelectric commented on src/VideoStreaming/SubtitleWriter.cc
> +"Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n");
You should do:
```
QStringLiteral(
    "[Script Info]\n"
    ...
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
);
```
This will avoid unnecessary changes in the diff while working with the first or last strings.

2019-05-16 19:27 UTC, patrickelectric commented on src/VideoStreaming/SubtitleWriter.cc
> +QString title_template = QStringLiteral("Dialogue: 0,0:00:00.00,999:00:00.00,Default,,0,0,0,,{\\pos(5,35)}%1\n");
Do not use global variables, make it static const inside the class.

2019-05-16 19:27 UTC, patrickelectric commented on src/VideoStreaming/SubtitleWriter.cc
> +{
you can also use `= default` in the place of empty brackets.

2019-05-16 19:27 UTC, patrickelectric commented on src/VideoStreaming/SubtitleWriter.cc
> +void SubtitleWriter::setup()
Connects should be done in the constructor if the pointers are already available, such as:
```
qgcApp()->toolbox()->videoManager()->videoReceiver();
```
You should also check if this pointer is not nullptr and emit a warning message about it.
Since this class is used inside `VideoManager` you can also get the pointer from it.

2019-05-16 19:27 UTC, patrickelectric commented on src/VideoStreaming/SubtitleWriter.cc
> +    if(!qgcApp()->toolbox()->videoManager()->videoReceiver()->recording()) {
you need to check again if videoReceiver pointer is valid.

2019-05-16 19:27 UTC, patrickelectric commented on src/VideoStreaming/SubtitleWriter.cc
> +        _lastEndTime = QTime(0,0);
`0, 0`

2019-05-16 19:27 UTC, patrickelectric commented on src/VideoStreaming/SubtitleWriter.cc
> +    _values = settings.value(_largeValuesKey, largeDefaults).toStringList().replaceInStrings("Vehicle.", "");
`(QStringLiteral("Vehicles"), QString())`

2019-05-16 19:27 UTC, patrickelectric commented on src/VideoStreaming/SubtitleWriter.cc
> +    QString subtitleFilePath = videoFile.path() + "/" + videoFile.completeBaseName() + ".ass";
`QStringLiteral("%1/%2.ass").arg(videoFile.path(), videoFile.completeBaseName())`

2019-05-16 19:27 UTC, patrickelectric commented on src/VideoStreaming/SubtitleWriter.cc
> +    }
```
else {
Not possible to write subtitle file.
}
```

2019-05-16 19:27 UTC, patrickelectric commented on src/VideoStreaming/SubtitleWriter.cc
> +        stream << date_template.arg(QDate::currentDate().toString("d MMM yyyy"));
I believe that `dd` will make it better, all files will have the same number of characters and will be easy to figure out the order.
Different operating systems do alphabetic or global sort for files, using `dd` will also fix that.
E.g:
```
1
10
11
2
20
21
```
vs
```
01
02
10
11
20
21
```

2019-05-16 19:27 UTC, patrickelectric commented on src/VideoStreaming/SubtitleWriter.cc
> +    if (vehicle) {
There is 40 lines inside this if, check if vehicle is not valid first and return with a error/warning message and after that do the normal logic.

2019-05-16 19:27 UTC, patrickelectric commented on src/VideoStreaming/SubtitleWriter.cc
> +        QString startTimeString = _lastEndTime.toString("H:mm:ss.zzz").chopped(2);
If you want it shopped why you don't remove the last two chars of the format string ?

2019-05-16 19:27 UTC, patrickelectric commented on src/VideoStreaming/SubtitleWriter.h
> +    static const int rows;
To avoid math operations that you are doing, use float.

2019-05-16 19:27 UTC, patrickelectric commented on src/VideoStreaming/SubtitleWriter.cc
> +        }
Missing else and warning message about failing to write to the subtitle file.

2019-05-16 19:27 UTC, patrickelectric commented on src/VideoStreaming/SubtitleWriter.cc
> +            QTextStream stream( &_file );
Why there is space around &file ? be consistent with the file and project style.

2019-05-16 21:16 UTC, Williangalvani commented on src/VideoStreaming/SubtitleWriter.cc
> +        QString startTimeString = _lastEndTime.toString("H:mm:ss.zzz").chopped(2);
https://doc.qt.io/qt-5/qtime.html#fromString-1

 > "s.z" reports the seconds to full available (millisecond) precision without trailing zeroes.

2019-05-16 21:25 UTC, Williangalvani commented on src/VideoStreaming/SubtitleWriter.cc
> +        stream << date_template.arg(QDate::currentDate().toString("d MMM yyyy"));
This is just the human-readable date at the top corner of the subtitle. The date in the filename is setup to be the same as the video filename, so the players can locate them easily.

2019-05-16 21:40 UTC, Williangalvani commented on src/VideoStreaming/SubtitleWriter.cc
> +        QTime start = QTime(0,0).addMSecs(QDateTime::currentDateTime().time().msecsTo(_startTime.time()));
I believe I can get it working now that the precision is reduced. before that any gap (20ms or so) caused the subtitles to flicker.

2019-05-16 22:10 UTC, Williangalvani commented on src/VideoStreaming/SubtitleWriter.cc
> +                                       .arg(_lastEndTime.toString("H:mm:ss.zzz").chopped(2))
That will not respect the formatting. It will fall in this case https://doc.qt.io/qt-5/qtime.html#toString-1 and use HH:mm:ss, with no decimals for the seconds.

2019-05-16 22:10 UTC, Williangalvani commented on src/VideoStreaming/SubtitleWriter.cc
> +                                     .arg(_lastEndTime.toString("H:mm:ss.zzz").chopped(2))
same as above

2019-05-16 22:20 UTC, Williangalvani commented on src/VideoStreaming/SubtitleWriter.cc
> +void SubtitleWriter::setup()
The pointers are not available in the constructor, that is why I went this route.

2019-05-16 23:05 UTC, patrickelectric commented on qgroundcontrol.pro
> +
Unnecessary extra space.

2019-05-16 23:06 UTC, patrickelectric commented on src/VideoStreaming/SubtitleWriter.cc
> +void SubtitleWriter::setup()
So I think you should rename it to something like `setVideoReceiver` and get the videoReceiver pointer as a parameter, this will make this function more explicit about what it's doing and will also be compatible with future multiple subtitle creations.

2019-05-16 23:25 UTC, patrickelectric commented on src/VideoStreaming/SubtitleWriter.h
> +    void _onVideoRecordingChanged();
If the slot is public why there is an underscore ?

2019-05-17 00:52 UTC, Williangalvani commented on src/VideoStreaming/SubtitleWriter.cc
> +void SubtitleWriter::setup()
I like it!

2019-05-24 17:49 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +const QString SubtitleWriter::_namesLine = QStringLiteral("Dialogue: 0,%2,%3,Default,,0,0,0,,{\\an3\\pos(%1,1075)}%4\n");
When used only once, I prefer these strings be declared and defined where they are used.

2019-05-27 18:04 UTC, Williangalvani commented on src/VideoStreaming/SubtitleWriter.cc
> +const QString SubtitleWriter::_namesLine = QStringLiteral("Dialogue: 0,%2,%3,Default,,0,0,0,,{\\an3\\pos(%1,1075)}%4\n");
Check my last commit. Is this what you had in mind?

2019-05-28 17:34 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +    stream << blankFile;
```
stream << "asdfadfadsffadfa"
"aasdfadsfadsfa"
"adsfa;lsdkja";
```

2019-05-28 17:35 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +    stream << dateTemplate.arg(QDate::currentDate().toString("d MMM yyyy"));
`stream << QString("asdfasdfasdfadfasdfadsf").arg();`

2019-05-28 17:36 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +const QString SubtitleWriter::_namesLine = QStringLiteral("Dialogue: 0,%2,%3,Default,,0,0,0,,{\\an3\\pos(%1,1075)}%4\n");
close.

2019-05-28 17:46 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +    connect(
match Don's style here. ( and reduce LOC for the patch ;) )

2019-05-28 17:48 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +    QFileInfo videoFile(_videoReceiver->videoFile());
check videoReceiver for nullptr

2019-05-28 17:49 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +    if(!_videoReceiver->recording()) {
check videoreceiver for nullptr

2019-05-28 18:00 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +    _values = settings.value("large", largeDefaults).toStringList().replaceInStrings(QStringLiteral("Vehicle."), QString());
explain what you are doing here.

2019-05-28 18:01 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +    int nRows = 3; // number of rows used for displaying data
static const

2019-05-28 18:01 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +    int offsetFactor = 700; // Used to simulate a larger resolution and reduce the borders in the layout
static const

2019-05-28 18:02 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +    int rowWidth = (1920 + offsetFactor)/(nRows+1);
static const

2019-05-28 18:03 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.h
> +protected slots:
why not private?

2019-05-28 18:03 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.h
> +protected:
why not private?

2019-05-28 19:11 UTC, jaxxzer commented on src/VideoStreaming/SubtitleWriter.cc
> +    _values = settings.value("large", largeDefaults).toStringList().replaceInStrings(QStringLiteral("Vehicle."), QString());
(comments)

2019-05-28 22:36 UTC, jaxxzer commented on src/VideoStreaming/VideoReceiver.cc
> +            pThis->recordedVideoStarted();
It seems like the existing `recordingChanged` should be emitted here. Can we do that instead of adding a new signal?

Semantically, 'recordingChanged' and `recordingVideoStarted` should refer to the same event (thus having two signals is redundant), unless there is actually some distinction you **need** to make.

2019-05-28 23:42 UTC, Williangalvani commented on src/VideoStreaming/VideoReceiver.cc
> +            pThis->recordedVideoStarted();
`recordingChanged` is emited when the user clicks the record button. This is emitted when the first keyframe is found and the recorded video actually starts, so they can be a few seconds apart.
Maybe we should use a better name?

2019-05-29 03:30 UTC, jaxxzer commented on src/VideoStreaming/VideoReceiver.cc
> +            pThis->recordedVideoStarted();
Will it break anything if we move the recordingChanged emission to later on, when the recorded video actually starts? I'm assuming the ui will just not reflect the click on the record button (square) immediately. If that's a problem, then I suggest perhaps enumerating the possible states and doing something like `recordingChanged(newState)`, or simply (if you prefer) change `recordingVideoStarted -> firstFileFrame` .. or some better name.

2019-05-29 12:51 UTC, Williangalvani commented on src/VideoStreaming/VideoReceiver.cc
> +            pThis->recordedVideoStarted();
I think the feedback for the user is important, otherwise they will just keep clicking it again.
what about `gotFirstRecordingKeyFrame`?

2019-05-29 16:18 UTC, jaxxzer commented on src/VideoStreaming/VideoReceiver.cc
> +            pThis->recordedVideoStarted();
> gotFirstRecordingKeyFrame

fine

2019-05-29 16:18 UTC, jaxxzer commented
I believe this is ready for primetime. Thanks for working through all the review @Williangalvani

2019-05-29 18:00 UTC, jaxxzer commented on src/VideoStreaming/VideoReceiver.cc
> +VideoReceiver::getRecordingTime()
we've still got the original problem (`0.1` instead of `0.0`):
```
,0:00:01.0,0:00:02.0,Default,,0,0,0,,{\pos(960,1075)}0.03 v\N13:56:42 \N5/29/19 \N63.4426065 \N10.4229063 \N10 
Dialogue: 0,0:00:01.0,0:00:02.0,Default,,0,0,0,,{\an3\pos(1605,1075)}Temperature (1):\NTemperature (2):\NTemperature (3):\NRoll Rate:\NRoll:
Dialogue: 0,0:00:01.0,0:00:02.0,Default,,0,0,0,,{\pos(1615,1075)}33.74 C\N--.-- C\N--.-- C\N0.0 deg/s\N-140.2 deg
Dialogue: 0,0:00:02.1,0:00:03.1,Default,,0,0,0,,{\an3\pos(295,1075)}Depth:\NGround Speed:\NDive Time:\NCamera Tilt:\NTether Turns:\NRangefinder:
Dialogue: 0,0:00:02.1,0:00:03.1,Default,,0,0,0,,{\pos(305,1075)}0.0 m\N0.0 m/s\N00:00:00 \N50 %\N0 clockwise\N--.-- meters
Dialogue: 0,0:00:02.1,0:00
```

2019-05-29 18:01 UTC, jaxxzer commented on src/VideoStreaming/VideoReceiver.cc
> +VideoReceiver::getRecordingTime()
don't sweat this if it's time consuming to solve.

2019-05-29 19:19 UTC, Williangalvani commented on src/VideoStreaming/VideoReceiver.cc
> +VideoReceiver::getRecordingTime()
I think it is weird to mess with the synchronization to get round numbers. we would be shifting the data slightly in time just for the file to look better.

2019-05-30 18:03 UTC, closed without merging